#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : expat
Version  : 2.2.0
Release  : 22
URL      : http://downloads.sourceforge.net/expat/expat-2.2.0.tar.bz2
Source0  : http://downloads.sourceforge.net/expat/expat-2.2.0.tar.bz2
Summary  : expat XML parser
Group    : Development/Tools
License  : MIT
Requires: expat-bin
Requires: expat-lib
Requires: expat-doc
Patch1: cve-2016-4472.nopatch

%description
Expat, Release 2.2.0
This is Expat, a C library for parsing XML, written by James Clark.
Expat is a stream-oriented XML parser.  This means that you register
handlers with the parser before starting the parse.  These handlers
are called when the parser discovers the associated structures in the
document being parsed.  A start tag is an example of the kind of
structures for which you may register handlers.

%package bin
Summary: bin components for the expat package.
Group: Binaries

%description bin
bin components for the expat package.


%package dev
Summary: dev components for the expat package.
Group: Development
Requires: expat-lib
Requires: expat-bin
Provides: expat-devel

%description dev
dev components for the expat package.


%package doc
Summary: doc components for the expat package.
Group: Documentation

%description doc
doc components for the expat package.


%package lib
Summary: lib components for the expat package.
Group: Libraries

%description lib
lib components for the expat package.


%prep
%setup -q -n expat-2.2.0

%build
export LANG=C
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition -falign-functions=32 "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xmlwf

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
